"""Add OccupancyPeriod model

Revision ID: 17a7204def9d
Revises: b6bf4355bfb3
Create Date: 2025-03-31 21:02:16.258940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a7204def9d'
down_revision = 'b6bf4355bfb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupancy_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('number_of_occupants', sa.Integer(), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date > start_date', name='check_occupancy_period_dates'),
    sa.CheckConstraint('number_of_occupants > 0', name='check_positive_occupants'),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupancy_period', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occupancy_period_apartment_id'), ['apartment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_occupancy_period_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_occupancy_period_start_date'), ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancy_period', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occupancy_period_start_date'))
        batch_op.drop_index(batch_op.f('ix_occupancy_period_end_date'))
        batch_op.drop_index(batch_op.f('ix_occupancy_period_apartment_id'))

    op.drop_table('occupancy_period')
    # ### end Alembic commands ###
