"""Add contract_pdf_filename to Contract

Revision ID: 519d827e96ca
Revises: c8046d0f28e2
Create Date: 2025-03-31 17:10:34.341183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519d827e96ca'
down_revision = 'c8046d0f28e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_pdf_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_column('contract_pdf_filename')
    # ### end Alembic commands ###
