"""Add contract_pdf_filename to Contract

Revision ID: 519d827e96ca
Revises: c8046d0f28e2
Create Date: 2025-03-31 17:10:34.341183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519d827e96ca'
down_revision = 'c8046d0f28e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apartment_number'), ['number'], unique=True)

    op.create_table('cost_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('consumption_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('cost_type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ),
    sa.ForeignKeyConstraint(['cost_type_id'], ['cost_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_info', sa.String(length=200), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rent_amount', sa.Float(), nullable=False),
    sa.Column('index_clause_base_value', sa.Float(), nullable=True),
    sa.Column('index_clause_base_date', sa.Date(), nullable=True),
    sa.Column('contract_pdf_filename', sa.String(length=255), nullable=True),
    sa.CheckConstraint('end_date IS NULL OR end_date > start_date', name='check_contract_dates'),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract')
    op.drop_table('tenant')
    op.drop_table('consumption_data')
    op.drop_table('cost_type')
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apartment_number'))

    op.drop_table('apartment')
    # ### end Alembic commands ###
