"""Add ApartmentShare model

Revision ID: b6bf4355bfb3
Revises: 519d827e96ca
Create Date: 2025-03-31 17:44:00.504093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bf4355bfb3'
down_revision = '519d827e96ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('cost_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ),
    sa.ForeignKeyConstraint(['cost_type_id'], ['cost_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apartment_id', 'cost_type_id', name='uq_apartment_cost_type_share')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apartment_share')
    # ### end Alembic commands ###
