"""add entry_type to consumption_data

Revision ID: c37155871e54
Revises: 17a7204def9d
Create Date: 2025-04-01 09:23:03.105577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c37155871e54'
down_revision = '17a7204def9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumption_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_type', sa.String(length=20), server_default='csv_import', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumption_data', schema=None) as batch_op:
        batch_op.drop_column('entry_type')

    # ### end Alembic commands ###
